/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:b65b6456-be80-4c00-9e8f-c46bb0c44188",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_RLYP0TBYB",
    "aws_user_pools_web_client_id": "7cr8jsevir66n08q2va1qusjhl",
    "oauth": {
        "domain": "univclassscheduler66379920-66379920-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://univ-classroom-scheduler-bucket.s3-website-us-east-1.amazonaws.com/admin/",
        "redirectSignOut": "https://univ-classroom-scheduler-bucket.s3-website-us-east-1.amazonaws.com/admin/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "Auth": {
        "identityPoolId": "us-east-2:b65b6456-be80-4c00-9e8f-c46bb0c44188",
        "region": "us-east-2",
        "userPoolId": "us-east-2_RLYP0TBYB",
        "userPoolWebClientId": "7cr8jsevir66n08q2va1qusjhl"
    }
};


export default awsmobile;
